apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.0.28
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: kolo-test-control-plane
    targetRef:
      kind: Pod
      name: kolo-backend-7696dd545f-frwrz
      namespace: cc03-test
      uid: 16562d5e-1668-4d7f-8b23-bf3646d5605c
  - addresses:
    - 10.244.0.29
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: kolo-test-control-plane
    targetRef:
      kind: Pod
      name: kolo-backend-7696dd545f-669b6
      namespace: cc03-test
      uid: 5d792a57-9d5c-4279-b71e-109e44cd8ce4
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-09-05T10:52:14Z"
    creationTimestamp: "2026-09-05T10:52:15Z"
    generateName: kolo-backend-svc-
    generation: 90
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: kolo-backend-svc
    name: kolo-backend-svc-p5886
    namespace: cc03-test
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kolo-backend-svc
      uid: 61393736-23f0-437b-a856-17793a3b9403
    resourceVersion: "12846"
    uid: d4649786-505b-4435-808a-46c68411781b
  ports:
  - name: ""
    port: 8000
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
